version: '3.8'
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
      
volumes:
  mysql-data:
