# Dockerfile

# MySQL 이미지를 기반으로 이미지 생성
FROM mysql:latest

# MySQL 설정
ENV DATABASE_PASSWORD=my-secret-pw
ENV DATABASE_NAME=mydb
ENV DATABASE_USERNAME=myuser
ENV DATABASE_PASSWORD=mypassword

# 포트 설정 (기본 MySQL 포트는 3306)
EXPOSE 3306