name: Docker Image CI

on:
  push:
    branches: ['main']

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: knori-github-s3-bucket
  CODE_DEPLOY_APPLICATION_NAME: knori-codedepoly-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: knori-code-group

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t manaweb-api .
      - name: taging
        run: docker tag manaweb-api:latest mag123c/manaweb-api:latest
      - name: Push to Dockerhub
        run: docker push mag123c/manaweb-api:latest
